---
- name: Configure SNMP community and host on a Cisco IOS router
  hosts: arista
  gather_facts: false
  vars:
    ansible_persistent_log_messages: true
    ansible_log_path: ~/ansible.log
  tasks:
    - name: Configure SNMP community and host
      arista.eos.eos_command:
        commands: show version
    - ansible.builtin.command: cat /tmp/ansible.log

- name: Push persistent logs
  hosts: log-server
  gather_facts: false
  tasks:
   - name: Upload persistent logs
     ansible.builtin.copy:
       src: ~/ansible.log
       dest: ansible.log
